### ISSUE TITLE
AttributeError: 'list' object has no attribute 'items'

### ISSUE THREAD

**Issue by RasmusMalver** [abhaykatheria/json2tree#7]
Regardless of input, I get this error. Python 3.11.6 on MacOS Sonoma 14.2 (23C64).

```zsh
$ json2tree -j base.json -o output.html

Traceback (most recent call last):
  File "~/folder/bin/json2tree", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "~/folder/lib/python3.11/site-packages/json2tree/__main__.py", line 62, in main
    run(args)
  File "~/folder/lib/python3.11/site-packages/json2tree/__main__.py", line 31, in run
    html_string = readJSON(args.json, args.theme)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/folder/lib/python3.11/site-packages/json2tree/__main__.py", line 18, in readJSON
    html_string = html_1.create_html_report(json_data)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/folder/lib/python3.11/site-packages/json2tree/theme_1/html.py", line 104, in create_html_report
    report = report + '\n' + report_dict_to_html(report_dict)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/folder/lib/python3.11/site-packages/json2tree/theme_1/html.py", line 95, in report_dict_to_html
    html_string = html_string + dict_handler(dict_obj, 0)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/folder/lib/python3.11/site-packages/json2tree/theme_1/html.py", line 63, in dict_handler
    for k, v in dict_obj.items():
                ^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'items'
```

I tried with a base file, containing just:
```json
[{"a":"b"}]
```

**Comment by abhaykatheria** [comment]
Fixed in new release
